POST  http://localhost:3000/register
Content-Type: application/json

{   
    "name":"prashanth",
    "username":"rahul12345",
    "password": "rahul@456",
    "gender": "Male",
    "location":"siddipet"
}
###

POST  http://localhost:3000/register 
Content-Type: application/json

{   
    "name":"prashanth",
    "username":"prashanth",
    "password": "ra123",
    "gender": "Male",
    "location":"siddipet"
}
###
POST  http://localhost:3000/login
Content-Type: application/json

{   
    "username":"prashanth",
    "password": "evb689"
}
###

PUT  http://localhost:3000/change-password 
Content-Type: application/json

{   
    "username":"prashanth",
    "oldPassword": "evb589",
    "newPassword": "evb689"
}


